// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:929717154070:web:81452a218f7777b1412037',
    messagingSenderId: '929717154070',
    projectId: 'flutter-chatapp-bam',
    authDomain: 'flutter-chatapp-bam.firebaseapp.com',
    storageBucket: 'flutter-chatapp-bam.appspot.com',
    measurementId: 'G-ZJHQFP4GC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:929717154070:android:e3abdd1a9c97c77e412037',
    messagingSenderId: '929717154070',
    projectId: 'flutter-chatapp-bam',
    storageBucket: 'flutter-chatapp-bam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:929717154070:ios:af5580bda946b3b7412037',
    messagingSenderId: '929717154070',
    projectId: 'flutter-chatapp-bam',
    storageBucket: 'flutter-chatapp-bam.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:929717154070:ios:af5580bda946b3b7412037',
    messagingSenderId: '929717154070',
    projectId: 'flutter-chatapp-bam',
    storageBucket: 'flutter-chatapp-bam.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '-qo',
    appId: '1:929717154070:web:f9e4f630b35a5aa1412037',
    messagingSenderId: '929717154070',
    projectId: 'flutter-chatapp-bam',
    authDomain: 'flutter-chatapp-bam.firebaseapp.com',
    storageBucket: 'flutter-chatapp-bam.appspot.com',
    measurementId: 'G-0Q1F6ETTF5',
  );
}
